⤵️ automation(synchronize) Applying changes from upstream repository.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -8,12 +8,13 @@ includes:
   ansible:populate: ./.config/taskfiles/ansible/Taskfile-populate.yml
   ansible:test: ./.config/taskfiles/ansible/Taskfile-test.yml
   boilerplate: ./.config/taskfiles/boilerplate/Taskfile.yml
+  boilerplate:prompt: ./.config/taskfiles/boilerplate/Taskfile-prompt.yml
   ci: ./.config/taskfiles/ci/Taskfile.yml
   ci:github: ./.config/taskfiles/ci/Taskfile-github.yml
-  common: ./.config/taskfiles/common/Taskfile.yml
   project:
     taskfile: Taskfile-project.yml
     optional: true
+  common: ./.config/taskfiles/common/Taskfile.yml
   common:code: ./.config/taskfiles/common/Taskfile-code.yml
   common:update: ./.config/taskfiles/common/Taskfile-update.yml
   docker: ./.config/taskfiles/docker/Taskfile.yml
@@ -124,6 +125,7 @@ profile: |
 tasks:
   build:
     deps:
+      - :install:software:jq
       - :install:software:node
     desc: Build the project
     summary: |
@@ -131,12 +133,19 @@ tasks:
 
       Use this command to build the project. It executes the command defined
       in `package.json` under the `.scripts.build` key.
+    vars:
+      NONINTERACTIVE_MISSING_BUILD_CMD: There must be a build command under `.scripts.build` in `package.json`!
     log:
       error: Encountered error while running `npm run build`
       start: Running `npm run build`
       success: Successfully ran `npm run build`
     cmds:
-      - npm run build
+      - |
+        if [ "$(jq '.scripts.build' package.json)" != 'null' ]; then
+          npm run build
+        else
+          [[ $- == *i* ]] && task prepare || (.config/log error '{{.NONINTERACTIVE_MISSING_BUILD_CMD}}' && exit 1)
+        fi
 
   cmds:
     - |
@@ -438,5 +447,12 @@ tasks:
 
       This task calls `npm run test` which functions differently based on the
       definition made in `package.json` under the `.scripts.test` key.
+    vars:
+      NONINTERACTIVE_MISSING_TEST_CMD: There must be a `.scripts.test` definition in `package.json`!
     cmds:
-      - npm run test
+      - |
+        if [ "$(jq '.scripts.test' package.json)" != 'null' ]; then
+          npm run test
+        else
+          [[ $- == *i* ]] && task prepare || (.config/log error '{{.NONINTERACTIVE_MISSING_TEST_CMD}}' && exit 1)
+        fi
