Update files/.husky/pre-commit

diff --git a/files/.husky/pre-commit b/files/.husky/pre-commit
--- a/files/.husky/pre-commit
+++ b/files/.husky/pre-commit
@@ -8,6 +8,10 @@ npx lint-staged
 log "Running npm test"
 npm test
 log "Checking for spelling errors"
-files=$(git diff --cached --name-only)
-npx cspell --no-summary --config ./.modules/shared/.cspell.json $files || warn "Possible spelling errors were found. Review the list of possible misspelled words above and correct anything that needs changing."
+FILES=$(git diff --cached --name-only)
+if [ "$FILES" ]; then
+  npx cspell --no-summary --config ./.modules/shared/.cspell.json $FILES || warn "Possible spelling errors were found. Review the list of possible misspelled words above and correct anything that needs changing."
+else
+  info "No files staged for spell checking"
+fi
 success "Successfully passed all validation checks"
