⤵️ automation(synchronize) Applying changes from upstream repository.

diff --git a/.config/docs/Taskfile.yml b/.config/docs/Taskfile.yml
--- a/.config/docs/Taskfile.yml
+++ b/.config/docs/Taskfile.yml
@@ -4,8 +4,8 @@ version: '3'
 output: interleaved
 
 vars:
-  DOCKERHUB_PROFILE: {{profile.dockerhub}}
-  DOCKERHUB_USER: {{profile.dockerHubUser}}
+  DOCKERHUB_PROFILE: megabytelabs
+  DOCKERHUB_USER: professormanhattan
   ESLINT_FIX_RECURSIVE: 'true'
   ESLINT_FORMATTER: stylish
   ESLINT_FORMATTER_OPTIONS: git-log gitlab pretty summary
@@ -16,12 +16,12 @@ vars:
       if [ -f meta/main.yml ]; then
         grep namespace < meta/main.yml | sed 's/.*namespace: \\(.*\\)$/\\1/g'
       else
-        echo '{{profile.galaxy}}'
+        echo 'professormanhattan'
       fi
   GALAXY_ROLE_NAME:
     sh: "if [ -f meta/main.yml ]; then grep role_name < meta/main.yml | sed 's/.*role_name: \\(.*\\)$/\\1/g'; fi"
-  GITHUB_ORG: {{profile.github}}
-  GITHUB_USER: {{profile.github}}
+  GITHUB_ORG: ProfessorManhattan
+  GITHUB_USER: ProfessorManhattan
   GROUP_EXEC_ASYNC: 'false'
   IGNORE_FOLDERS: -path './.autodoc/*' -o -path './.cache/*' -o -path './.common*' -o -path './.config/*' -o -path './.git/*'
     -o -path './.github/*' -o -path './.gitlab/*' -o -path './.husky/*' -o -path './.modules/*' -o -path './.npm/*'
@@ -41,9 +41,9 @@ vars:
   PROJECT_TYPE:
     sh: |
       # yamllint disable-line rule:line-length
-      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.group' package.json)"; if [ "$VER" == 'null' ]; then echo TYPE="{{group}}"; else TYPE="$VER"; fi; else TYPE="{{group}}"; fi
+      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.group' package.json)"; if [ "$VER" == 'null' ]; then echo TYPE="common"; else TYPE="$VER"; fi; else TYPE="common"; fi
       # yamllint disable-line rule:line-length
-      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.subgroup' package.json)"; if [ "$VER" == 'null' ]; then SUBTYPE="{{subgroup}}"; else SUBTYPE="$VER"; fi; else SUBTYPE="{{subgroup}}"; fi
+      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.subgroup' package.json)"; if [ "$VER" == 'null' ]; then SUBTYPE="packer"; else SUBTYPE="$VER"; fi; else SUBTYPE="packer"; fi
       if [ "$TYPE" == 'common' ] && [ "$SUBTYPE" == 'shared' ]; then
         echo 'shared'
       elif [ "$TYPE" == 'common' ]; then
@@ -62,17 +62,17 @@ vars:
     sh: |
       if type jq &> /dev/null && [ -f package.json ]; then
         VER="$(jq -r '.blueprint.subgroup' package.json)"
-        if [ "$VER" == 'null' ]; then echo "{{subgroup}}"; else echo "$VER"; fi
+        if [ "$VER" == 'null' ]; then echo "packer"; else echo "$VER"; fi
       else
-        echo "{{subgroup}}"
+        echo "packer"
       fi
   REPOSITORY_TYPE:
     sh: |
       if type jq &> /dev/null && [ -f package.json ]; then
         VER="$(jq -r '.blueprint.group' package.json)"
-        if [ "$VER" == 'null' ]; then echo "{{group}}"; else echo "$VER"; fi
+        if [ "$VER" == 'null' ]; then echo "common"; else echo "$VER"; fi
       else
-        echo "{{group}}"
+        echo "common"
       fi
   SEMANTIC_CONFIG: semantic-release-config
   TIMEZONE: America/New_York
@@ -80,10 +80,10 @@ vars:
 env:
   OSTYPE:
     sh: |
-      \{{if (eq OS "linux")}}LINUX_FLAVOR='linux-gnu'
+      {{if (eq OS "linux")}}LINUX_FLAVOR='linux-gnu'
       LIBC=$(ldd /bin/ls | grep 'musl' | head -1 | cut -d ' ' -f1)
-      if [ -n "$LIBC" ]; then LINUX_FLAVOR='linux-musl'; fi\{{end}}
-      echo "\{{if (eq OS "linux")}}$LINUX_FLAVOR\{{else}}darwin\{{end}}"
+      if [ -n "$LIBC" ]; then LINUX_FLAVOR='linux-musl'; fi{{end}}
+      echo "{{if (eq OS "linux")}}$LINUX_FLAVOR{{else}}darwin{{end}}"
   RECORD_INSTALL:
     sh: if [ -n "$CI" ]; then echo 'true'; fi
   SENTRY_DSN:
@@ -92,13 +92,87 @@ env:
       if [ "$DSN" != 'null' ]; then echo "$DSN"; fi
 
 includes:
-{{#forEach (bodegaIncludes)}}
-  {{key}}:{{#if (not optional)}} {{taskPath}}{{/if}}
-  {{#if optional}}
-    taskfile: {{taskPath}}
-    optional: true
-  {{/if}}
-{{/forEach}}
+  ansible: ./.config/taskfiles/ansible/Taskfile.yml
+  ansible:ansibler: ./.config/taskfiles/ansible/Taskfile-ansibler.yml
+  ansible:playbook: ./.config/taskfiles/ansible/Taskfile-playbook.yml
+  ansible:populate: ./.config/taskfiles/ansible/Taskfile-populate.yml
+  ansible:test: ./.config/taskfiles/ansible/Taskfile-test.yml
+  app: ./.config/taskfiles/app/Taskfile.yml
+  app:virtualbox: ./.config/taskfiles/app/Taskfile-virtualbox.yml
+  boilerplate: ./.config/taskfiles/boilerplate/Taskfile.yml
+  boilerplate:populate: ./.config/taskfiles/boilerplate/Taskfile-populate.yml
+  boilerplate:prompt: ./.config/taskfiles/boilerplate/Taskfile-prompt.yml
+  ci: ./.config/taskfiles/ci/Taskfile.yml
+  ci:github: ./.config/taskfiles/ci/Taskfile-github.yml
+  common: ./.config/taskfiles/common/Taskfile.yml
+  common:code: ./.config/taskfiles/common/Taskfile-code.yml
+  common:update: ./.config/taskfiles/common/Taskfile-update.yml
+  common:util: ./.config/taskfiles/common/Taskfile-util.yml
+  docker: ./.config/taskfiles/docker/Taskfile.yml
+  docker:build: ./.config/taskfiles/docker/Taskfile-build.yml
+  docker:test: ./.config/taskfiles/docker/Taskfile-test.yml
+  docker:update: ./.config/taskfiles/docker/Taskfile-update.yml
+  fix: ./.config/taskfiles/fix/Taskfile.yml
+  git: ./.config/taskfiles/git/Taskfile.yml
+  git:github: ./.config/taskfiles/git/Taskfile-github.yml
+  git:gitlab: ./.config/taskfiles/git/Taskfile-gitlab.yml
+  git:hook: ./.config/taskfiles/git/Taskfile-hook.yml
+  go: ./.config/taskfiles/go/Taskfile.yml
+  go:goreleaser: ./.config/taskfiles/go/Taskfile-goreleaser.yml
+  go:test: ./.config/taskfiles/go/Taskfile-test.yml
+  image: ./.config/taskfiles/image/Taskfile.yml
+  install: ./.config/taskfiles/install/Taskfile.yml
+  install:ansible: ./.config/taskfiles/install/Taskfile-ansible.yml
+  install:apt: ./.config/taskfiles/install/Taskfile-apt.yml
+  install:github: ./.config/taskfiles/install/Taskfile-github.yml
+  install:go: ./.config/taskfiles/install/Taskfile-go.yml
+  install:npm: ./.config/taskfiles/install/Taskfile-npm.yml
+  install:pipx: ./.config/taskfiles/install/Taskfile-pipx.yml
+  install:python: ./.config/taskfiles/install/Taskfile-python.yml
+  install:rust: ./.config/taskfiles/install/Taskfile-rust.yml
+  install:software: ./.config/taskfiles/install/Taskfile-software.yml
+  lint: ./.config/taskfiles/lint/Taskfile.yml
+  lint:codeclimate: ./.config/taskfiles/lint/Taskfile-codeclimate.yml
+  lint:esprint: ./.config/taskfiles/lint/Taskfile-esprint.yml
+  lint:markdown: ./.config/taskfiles/lint/Taskfile-markdown.yml
+  lint:prose: ./.config/taskfiles/lint/Taskfile-prose.yml
+  log: ./.config/taskfiles/log/Taskfile.yml
+  nest: ./.config/taskfiles/nest/Taskfile.yml
+  npm: ./.config/taskfiles/npm/Taskfile.yml
+  npm:bundle: ./.config/taskfiles/npm/Taskfile-bundle.yml
+  npm:cov: ./.config/taskfiles/npm/Taskfile-cov.yml
+  npm:doc: ./.config/taskfiles/npm/Taskfile-doc.yml
+  packer: ./.config/taskfiles/packer/Taskfile.yml
+  packer:build: ./.config/taskfiles/packer/Taskfile-build.yml
+  packer:update: ./.config/taskfiles/packer/Taskfile-update.yml
+  publish: ./.config/taskfiles/publish/Taskfile.yml
+  publish:android: ./.config/taskfiles/publish/Taskfile-android.yml
+  publish:brew: ./.config/taskfiles/publish/Taskfile-brew.yml
+  publish:chrome: ./.config/taskfiles/publish/Taskfile-chrome.yml
+  publish:firefox: ./.config/taskfiles/publish/Taskfile-firefox.yml
+  publish:ios: ./.config/taskfiles/publish/Taskfile-ios.yml
+  publish:menubar: ./.config/taskfiles/publish/Taskfile-menubar.yml
+  publish:opera: ./.config/taskfiles/publish/Taskfile-opera.yml
+  publish:snap: ./.config/taskfiles/publish/Taskfile-snap.yml
+  python: ./.config/taskfiles/python/Taskfile.yml
+  python:test: ./.config/taskfiles/python/Taskfile-test.yml
+  release: ./.config/taskfiles/release/Taskfile.yml
+  security: ./.config/taskfiles/security/Taskfile.yml
+  symlink: ./.config/taskfiles/symlink/Taskfile.yml
+  ui: ./.config/taskfiles/ui/Taskfile.yml
+  update: ./.config/taskfiles/update/Taskfile.yml
+  upstream: ./.config/taskfiles/upstream/Taskfile.yml
+  upstream:common: ./.config/taskfiles/upstream/Taskfile-common.yml
+  upstream:commondocs: ./.config/taskfiles/upstream/Taskfile-commondocs.yml
+  upstream:docs: ./.config/taskfiles/upstream/Taskfile-docs.yml
+  upstream:project: ./.config/taskfiles/upstream/Taskfile-project.yml
+  upstream:shared: ./.config/taskfiles/upstream/Taskfile-shared.yml
+  vagrant: ./.config/taskfiles/vagrant/Taskfile.yml
+  vscode: ./.config/taskfiles/vscode/Taskfile.yml
+  web: ./.config/taskfiles/web/Taskfile.yml
+  web:ionic: ./.config/taskfiles/web/Taskfile-ionic.yml
+  web:nx: ./.config/taskfiles/web/Taskfile-nx.yml
+  web:profile: ./.config/taskfiles/web/Taskfile-profile.yml
 
 profile: |
   PATH="$PATH:$HOME/.local/bin:$HOME/.poetry/bin"
@@ -142,7 +216,7 @@ tasks:
         if [ "$(jq '.scripts.build' package.json)" != 'null' ]; then
           npm run build
         else
-          [[ $- == *i* ]] && task prepare || (.config/log error '\{{.NONINTERACTIVE_MISSING_BUILD_CMD}}' && exit 1)
+          [[ $- == *i* ]] && task prepare || (.config/log error '{{.NONINTERACTIVE_MISSING_BUILD_CMD}}' && exit 1)
         fi
 
   clean:
@@ -160,7 +234,7 @@ tasks:
     cmds:
       - task: common:clean
         vars:
-          CLEAN_TARGETS: '\{{.CLEAN_TARGETS}}'
+          CLEAN_TARGETS: '{{.CLEAN_TARGETS}}'
 
   commit:
     desc: Lint staged files, report spelling errors, and open a _required_ commit dialoge
@@ -207,13 +281,13 @@ tasks:
       error: Error while running commit logic
     cmds:
       - |
-        \{{if .CLI_ARGS}}
+        {{if .CLI_ARGS}}
         git add --all
-        HUSKY=0 git commit -m "\{{.CLI_ARGS}}" --no-verify
-        \{{else}}
+        HUSKY=0 git commit -m "{{.CLI_ARGS}}" --no-verify
+        {{else}}
         git add --all
         git commit
-        \{{end}}
+        {{end}}
 
   commit:quick:
     cmds:
@@ -229,28 +303,7 @@ tasks:
 
   donothing: 'true'
 
-{{#eq group "ansible"}}{{#eq subgroup "playbook"}}
-  environment:
-    interactive: true
-    desc: Symlink to an environment in the `environments/` folder
-    summary: |
-      # Switch Environments Using an Interactive Dialogue
 
-      Ansible does not really provide any great ways to switch between environments (or sets of
-      `host_vars/`, `group_vars/` etc.). If you place all the files and folders you wish to constitute
-      as an environment inside a folder named as the name of the environment in the `environments/` folder
-      then you can use this task to handle the symlinking and switching between environments.
-
-      **Example of opening the interactive prompt:**
-      `task ansible:environment`
-
-      **You can directly switch enironments to `environments/prod/` by running:**
-      `task ansible:environment -- prod`
-    cmds:
-      - task: ansible:playbook:environment
-    build: |
-      yq eval -i -P '.tasks.environment.summary = $summary' .config/taskfiles/ansible/Taskfile.yml
-{{/eq}}{{/eq}}
   fix:
     desc: Run code auto-fixers / auto-formatters
     summary: |
@@ -272,8 +325,8 @@ tasks:
       GITLAB_URL:
         sh: jq -r '.blueprint.repository.gitlab' package.json
     cmds:
-      - .config/log info 'GitHub -----> `\{{.GITHUB_URL}}`'
-      - .config/log info 'GitLab -----> `\{{.GITLAB_URL}}`'
+      - .config/log info 'GitHub -----> `{{.GITHUB_URL}}`'
+      - .config/log info 'GitLab -----> `{{.GITLAB_URL}}`'
 
   group:exec:
     desc: Execute group commands on any GitLab group (including repositories in sub-groups)
@@ -319,7 +372,7 @@ tasks:
 
       You can control the initialization script that this task runs by specifying
       `UPDATE_INIT_SCRIPT` as an environment variable. If it is not specified, then this
-      task runs the [default script](\{{.INIT_SCRIPT}}).
+      task runs the [default script]({{.INIT_SCRIPT}}).
     log:
       start: Initializing project by running initialization script
       success: Successfully bootstrapped project by running initialization script
@@ -382,7 +435,7 @@ tasks:
         if [ ! -f Taskfile-project.yml ]; then
           .config/log error '`Taskfile-project.yml` must exist and have a `livereload` task to use with `nodemon`' && exit 1
         fi
-      - nodemon --config \{{if .CLI_ARGS}}\{{.CLI_ARGS}}\{{else}}.config/nodemon.json\{{end}}
+      - nodemon --config {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.config/nodemon.json{{end}}
 
   new:project:
     desc: Create a new project
@@ -439,7 +492,7 @@ tasks:
 
   publish:force:
     vars:
-      UPDATE_LEVEL: '\{{if .CLI_ARGS}}\{{.CLI_ARGS}}\{{else}}PATCH UPDATE\{{end}}'
+      UPDATE_LEVEL: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}PATCH UPDATE{{end}}'
     desc: Force a `semantic-release` even if there are no new eligible commits
     summary: |
       # Force a Release with Empty Commit
@@ -463,31 +516,9 @@ tasks:
       success: Successfully published update via `task publish:force`
     cmds:
       - |
-        HUSKY=0 git commit -a --allow-empty -m '🔨 build(version bump): semantic-release \{{.UPDATE_LEVEL}}' -n
+        HUSKY=0 git commit -a --allow-empty -m '🔨 build(version bump): semantic-release {{.UPDATE_LEVEL}}' -n
       - task: publish
-{{#eq group 'ansible'}}{{#eq subgroup 'playbook'}}
-  playbook:
-    desc: Run the playbook
-    summary: |
-      # Run the Playbook
 
-      This task will prompt you for the environment and inventory you would like to
-      run the `main.yml` playbook with. It will:
-
-      1. Symlink all roles in the `roles/` folder to `~/.ansible/roles`
-      2. Run `task environment` (which prompts and symlinks the appropriate environment)
-      3. Prompt for which inventory to use
-      4. Run `ansible-playbook -i inventories/your_choice --ask-vault-pass main.yml`
-
-      **Example usage:**
-      `task playbook`
-
-      **Example bypassing prompts, using the `inventories/inventory.yml` file:**
-      `task playbook -- inventory.yml`
-    cmds:
-      - task: ansible:playbook:run
-
-{{/eq}}{{/eq}}
   preload:
     desc: Set up your workstation in advance by installing commonly used programs
     summary: |
@@ -498,7 +529,7 @@ tasks:
       a handful of CLIs (and Python). This task will check for missing applications
       and install them globally. If you do not run this task, the routines will
       assume you want to keep the footprint small and use disposable virtual
-      environments whenever possible (i.e. `\{{.NPX_PACKAGE}}` in the case of Node.js,
+      environments whenever possible (i.e. `{{.NPX_PACKAGE}}` in the case of Node.js,
       `poetry` in the case of Python, etc.).
 
       ## Reboot Requirements
@@ -551,14 +582,14 @@ tasks:
   repair:
     cmds:
       - |
-        TMP="$(mktemp)" && curl -sSL \{{.MODEL_TASKFILE}} > "$TMP"
+        TMP="$(mktemp)" && curl -sSL {{.MODEL_TASKFILE}} > "$TMP"
         .config/log info 'Ensuring new additions to the model `Taskfile.yml` are present in the project `Taskfile.yml`'
         yq eval-all -i 'select(fileIndex == 0) * select(fileIndex == 1)' "$TMP" Taskfile.yml
       - |
         if [ -n "$UPDATE_INIT_SCRIPT" ]; then
           bash <(curl -sSL "$UPDATE_INIT_SCRIPT")
         else
-          bash <(curl -sSL \{{.INIT_SCRIPT}})
+          bash <(curl -sSL {{.INIT_SCRIPT}})
         fi
 
   reset:
@@ -622,10 +653,10 @@ tasks:
       task is a convenience method that will present a list of scripts alongside
       their descriptions that you can interactively launch.
     log:
-      start: Running `NTL_RUNNER=\{{.NPM_PROGRAM}} \{{.NPX_HANDLE}}ntl`
-      error: Error running `NTL_RUNNER=\{{.NPM_PROGRAM}} \{{.NPX_HANDLE}}ntl`
+      start: Running `NTL_RUNNER={{.NPM_PROGRAM}} {{.NPX_HANDLE}}ntl`
+      error: Error running `NTL_RUNNER={{.NPM_PROGRAM}} {{.NPX_HANDLE}}ntl`
     cmds:
-      - NTL_RUNNER=\{{.NPM_PROGRAM}} \{{.NPX_HANDLE}}ntl
+      - NTL_RUNNER={{.NPM_PROGRAM}} {{.NPX_HANDLE}}ntl
 
   services:
     desc: Update elements of the repository that require API access
@@ -693,7 +724,7 @@ tasks:
       success: Successfully synchronized the project with upstream file changes and also bootstrapped the project
       error: Error encountered while starting up the project
     cmds:
-      - task: upstream:\{{.PROJECT_TYPE}}
+      - task: upstream:{{.PROJECT_TYPE}}
 
   tag:deps:
     desc: Inject a new command in the `Taskfile.yml` that includes all tasks matching a given tag as deps
@@ -737,11 +768,11 @@ tasks:
           FILE="$1"
           TMP="$(mktemp)"
           .config/log info 'Generating `'"${FILE//.liquid}"'` from `'"$FILE"'`'
-          \{{.NPX_HANDLE}}hbs --data .variables.json --helper ./.config/hbs.cjs "$FILE" --stdout > "$TMP"
+          {{.NPX_HANDLE}}hbs --data .variables.json --helper ./.config/hbs.cjs "$FILE" --stdout > "$TMP"
           mv "$TMP" "${FILE//.liquid}"
           rm "$FILE"
         }
-        handlebars '\{{.CLI_ARGS}}'
+        handlebars '{{.CLI_ARGS}}'
     preconditions:
       - sh: test -f .variables.json
         msg: This task requires that you have already spun up the project by running `task start`
@@ -759,24 +790,12 @@ tasks:
 
       This task calls `npm run test` which functions differently based on the
       definition made in `package.json` under the `.scripts.test` key.
-      {{#eq group "ansible"}}
-      ## Ansible Project Functionality
-
-      For Ansible projects, this task wraps all the supported test methods for Ansible plays into a
-      convenient multi-question prompt system that supports:
-
-      1. Docker tests
-      2. Headless VirtualBox tests
-      3. VirtualBox Desktop tests which are not automatically destroyed
-      4. Running the play locally
-      5. Running the play over SSH on a remote target
-      {{/eq}}
     cmds:
       - |
         if [ "$(jq '.scripts.test' package.json)" != 'null' ]; then
           npm run test
         else
-          [[ $- == *i* ]] && task prepare || (.config/log error '\{{.NONINTERACTIVE_MISSING_TEST_CMD}}' && exit 1)
+          [[ $- == *i* ]] && task prepare || (.config/log error '{{.NONINTERACTIVE_MISSING_TEST_CMD}}' && exit 1)
         fi
 
   update:
